fragment pbSection on pageBuilder_pbSection_BlockType {
  typeHandle
  id
  baseTitle
  baseRichtext
}

fragment pbImageProps on images_Asset {
  id
  url @transform(width: 1024, height: 1024, mode: "fit", format: "jpg")
  title
  # imageAlt
}

fragment pbImage on pageBuilder_pbImage_BlockType {
  typeHandle
  id
  baseImage {
    ...pbImageProps
  }
}

fragment pbLink on pageBuilder_pbLink_BlockType {
  typeHandle
  id
  baseLink {
    customText
    target
    text
    title
    type
    url
  }
}
