fragment pbSection on pageBuilder_pbSection_BlockType {
  __typename
  id
  baseTitle
  baseRichtext
}

fragment pbImage on pageBuilder_pbImage_BlockType {
  __typename
  id
  baseImage {
    url
    width
    height
    title
  }
}

fragment pbLink on pageBuilder_pbLink_BlockType {
  __typename
  id
  baseLink {
    customText
    target
    text
    title
    type
    url
  }
}
