fragment pbSection on pageBuilder_pbSection_BlockType {
  typeHandle
  id
  baseTitle
  baseRichtext
}

fragment pbImage on pageBuilder_pbImage_BlockType {
  typeHandle
  id
  baseImage {
    url @transform(width: 768, height: 768, mode: "fit", format: "webp")
    title
  }
}

fragment pbLink on pageBuilder_pbLink_BlockType {
  typeHandle
  id
  baseLink {
    customText
    target
    text
    title
    type
    url
  }
}
