fragment seomatic on EntryInterface {
  seomatic(asArray: true) {
    metaTitleContainer
    metaTagContainer
    metaLinkContainer
    # metaScriptContainer
    # metaJsonLdContainer
    # metaSiteVarsContainer
  }
}
