[build]
  command = "yarn netlify"
  publish = "dist"

# Branch deploy with custom build command and publish directory (for example `storybook`):
# [context.storybook]
#   command = "yarn storybook:build"
#   publish = "storybook-static"
