query MainNav($navHandle: String, $site: [String]) {
  menu: nodes(navHandle: $navHandle, level: 1, site: $site) {
    title
    url
    nodeUri
    children {
      title
      url
      nodeUri
    }
  }
}
