query verbbNavigation($navHandle: String, $level: Int = 1, $site: [String]) {
  menu: nodes(navHandle: $navHandle, level: $level, site: $site) {
    id
    title
    url
    nodeUri
    children {
      id
      title
      url
      nodeUri
    }
  }
}
