fragment verbbNavigationNodeFields on NodeInterface {
  id
  title
  url
  nodeUri
  level
  newWindow
  type
}

query verbbNavigation($navHandle: String, $level: Int = 1, $site: [String]) {
  menu: nodes(navHandle: $navHandle, level: $level, site: $site) {
    ...verbbNavigationNodeFields
    children {
      ...verbbNavigationNodeFields
      children {
        ...verbbNavigationNodeFields
        children {
          ...verbbNavigationNodeFields
        }
      }
    }
  }
}
